"""Add stuff

Revision ID: 367e2d9461d7
Revises: 50f87eff0099
Create Date: 2018-07-17 16:44:37.435366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367e2d9461d7'
down_revision = '50f87eff0099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expressions_tags',
    sa.Column('expression_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expression_id'], ['expression.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('formalizations_expressions',
    sa.Column('formalization_id', sa.Integer(), nullable=True),
    sa.Column('expression_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expression_id'], ['expression.id'], ),
    sa.ForeignKeyConstraint(['formalization_id'], ['formalization.id'], )
    )
    op.drop_table('requirement')
    op.add_column('formalization', sa.Column('pattern_id', sa.Integer(), nullable=True))
    op.add_column('formalization', sa.Column('scope_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'formalization', 'scope', ['scope_id'], ['id'])
    op.create_foreign_key(None, 'formalization', 'pattern', ['pattern_id'], ['id'])
    op.drop_column('tag', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('order', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'formalization', type_='foreignkey')
    op.drop_constraint(None, 'formalization', type_='foreignkey')
    op.drop_column('formalization', 'scope_id')
    op.drop_column('formalization', 'pattern_id')
    op.create_table('requirement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pos_in_csv', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('formalizations_expressions')
    op.drop_table('expressions_tags')
    # ### end Alembic commands ###
