"""Add stuff

Revision ID: 50f87eff0099
Revises: 2bacde5658d3
Create Date: 2018-07-17 16:07:34.576714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f87eff0099'
down_revision = '2bacde5658d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'order')
    # ### end Alembic commands ###
