"""init

Revision ID: 9c908fe0f67c
Revises: 
Create Date: 2018-07-10 14:56:50.523891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c908fe0f67c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variable_name'), 'variable', ['name'], unique=False)
    op.create_index(op.f('ix_variable_type'), 'variable', ['type'], unique=False)
    op.create_table('expressions_variables',
    sa.Column('variable_id', sa.Integer(), nullable=True),
    sa.Column('expression_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expression_id'], ['expression.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variable.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expressions_variables')
    op.drop_index(op.f('ix_variable_type'), table_name='variable')
    op.drop_index(op.f('ix_variable_name'), table_name='variable')
    op.drop_table('variable')
    op.drop_table('expression')
    # ### end Alembic commands ###
