"""add Scope, Pattern, Formalization

Revision ID: a931bb0d202a
Revises: ed738a595805
Create Date: 2018-07-10 17:55:23.715081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a931bb0d202a'
down_revision = 'ed738a595805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formalization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_name'), 'pattern', ['name'], unique=False)
    op.create_table('scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_name'), 'scope', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scope_name'), table_name='scope')
    op.drop_table('scope')
    op.drop_index(op.f('ix_pattern_name'), table_name='pattern')
    op.drop_table('pattern')
    op.drop_table('formalization')
    # ### end Alembic commands ###
