"""add Scope Pattern Formalization

Revision ID: d422ac014a23
Revises: a931bb0d202a
Create Date: 2018-07-11 15:26:04.111186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd422ac014a23'
down_revision = 'a931bb0d202a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_color'), 'tag', ['color'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.add_column('pattern', sa.Column('pattern', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_pattern_pattern'), 'pattern', ['pattern'], unique=False)
    op.add_column('scope', sa.Column('scope', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_scope_scope'), 'scope', ['scope'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scope_scope'), table_name='scope')
    op.drop_column('scope', 'scope')
    op.drop_index(op.f('ix_pattern_pattern'), table_name='pattern')
    op.drop_column('pattern', 'pattern')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_color'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
