"""Add type_inference_error boolean to Expression

Revision ID: e1d378c78c9d
Revises: d422ac014a23
Create Date: 2018-07-11 15:30:04.006762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d378c78c9d'
down_revision = 'd422ac014a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expression', sa.Column('type_inference_error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expression', 'type_inference_error')
    # ### end Alembic commands ###
