"""add value to variable

Revision ID: ed738a595805
Revises: 9c908fe0f67c
Create Date: 2018-07-10 15:03:45.788029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed738a595805'
down_revision = '9c908fe0f67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('value', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variable', 'value')
    # ### end Alembic commands ###
