name: Make Typechecks
# This is just experimental at the moment
on: [push]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r ./hanfor/requirements-dev.txt -r ./hanfor/requirements.txt
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
